[env:ESP-LCD]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = ESP-LCD
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
	-DBOARD_HAS_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-D LV_CONF_PATH="${PROJECT_DIR}/lib/lv_conf.h"
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-DHYPURPLE_WIFI_SSID=\"${sysenv.HYPURPLE_WIFI_SSID}\"
	-DHYPURPLE_WIFI_PASSWORD=\"${sysenv.HYPURPLE_WIFI_PASSWORD}\"
	-DHYPURPLE_CONTROLLER_URL=\"http://hypurple-pi.local:8787\"
	-DHYPURPLE_SMART_KNOB_TOKEN=\"${sysenv.HYPURPLE_SMART_KNOB_TOKEN}\"
	-I src
	-I lib

lib_deps =
	https://github.com/lvgl/lvgl.git#release/v8.4
